# Generated by Django 4.1 on 2024-11-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=32, verbose_name='学院名称')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'fater_colleges',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=32, verbose_name='班级名称')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'fater_grades',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=32, verbose_name='科目名称')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'fater_projects',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('userName', models.CharField(db_column='user_name', max_length=32, verbose_name='用户账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=32, verbose_name='用户密码')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('type', models.IntegerField(verbose_name='用户身份 0-管理员 1-教师 2-学生')),
            ],
            options={
                'db_table': 'fater_users',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('record', models.CharField(max_length=10, verbose_name='教师学历 ')),
                ('job', models.CharField(max_length=20, verbose_name='教师职称')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='app.colleges')),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.CASCADE, to='app.grades')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_students',
            },
        ),
        migrations.CreateModel(
            name='Practises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=64, verbose_name='题目名称')),
                ('answer', models.TextField(verbose_name='参考答案')),
                ('analyse', models.TextField(verbose_name='题目分析')),
                ('type', models.IntegerField(verbose_name='题目类型 0-选择 1-填空 2-判断 3-编程')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
            ],
            options={
                'db_table': 'fater_practises',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=64, verbose_name='题目名称')),
                ('practise', models.ForeignKey(db_column='practise_id', on_delete=django.db.models.deletion.CASCADE, to='app.practises')),
            ],
            options={
                'db_table': 'fater_options',
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=64, verbose_name='考试名称')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
                ('examTime', models.CharField(db_column='exam_time', max_length=19, verbose_name='考试时间')),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.CASCADE, to='app.grades')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_exams',
            },
        ),
        migrations.CreateModel(
            name='ExamLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('status', models.IntegerField(verbose_name='考试状态 0-参考 1-待审 2-结束')),
                ('score', models.FloatField(default=0.0, verbose_name='考试得分')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='参考时间')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='app.exams')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_exam_logs',
            },
        ),
        migrations.CreateModel(
            name='AnswerLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('score', models.FloatField(default=0.0, verbose_name='审核分数')),
                ('status', models.IntegerField(verbose_name='审核结果 0-待审 1-结束')),
                ('answer', models.TextField(verbose_name='答案内容')),
                ('no', models.IntegerField(verbose_name='题号索引')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='app.exams')),
                ('practise', models.ForeignKey(db_column='practises_id', on_delete=django.db.models.deletion.CASCADE, to='app.practises')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_answer_logs',
            },
        ),
    ]
