# Generated by Django 5.2.5 on 2025-08-11 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250811_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereads',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),

        migrations.AlterField(
            model_name='wrongquestions',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
    ]
