# Generated by Django 5.2.5 on 2025-08-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentpracticeanswers_aianalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='endTime',
            field=models.CharField(db_column='end_time', max_length=19, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='exams',
            name='startTime',
            field=models.CharField(db_column='start_time', max_length=19, null=True, verbose_name='开始时间'),
        ),
    ]
