# Generated by Django 4.1.3 on 2025-11-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_exams_endtime_exams_starttime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answerlogs',
            index=models.Index(fields=['student'], name='idx_answerlogs_student'),
        ),
        migrations.AddIndex(
            model_name='answerlogs',
            index=models.Index(fields=['exam'], name='idx_answerlogs_exam'),
        ),
        migrations.AddIndex(
            model_name='answerlogs',
            index=models.Index(fields=['practise'], name='idx_answerlogs_practise'),
        ),
        migrations.AddIndex(
            model_name='answerlogs',
            index=models.Index(fields=['status'], name='idx_answerlogs_status'),
        ),
        migrations.AddIndex(
            model_name='examlogs',
            index=models.Index(fields=['student'], name='idx_examlogs_student'),
        ),
        migrations.AddIndex(
            model_name='examlogs',
            index=models.Index(fields=['exam'], name='idx_examlogs_exam'),
        ),
        migrations.AddIndex(
            model_name='examlogs',
            index=models.Index(fields=['status'], name='idx_examlogs_status'),
        ),
        migrations.AddIndex(
            model_name='examlogs',
            index=models.Index(fields=['createTime'], name='idx_examlogs_createtime'),
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['teacher'], name='idx_exams_teacher'),
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['project'], name='idx_exams_project'),
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['grade'], name='idx_exams_grade'),
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['createTime'], name='idx_exams_createtime'),
        ),
        migrations.AddIndex(
            model_name='options',
            index=models.Index(fields=['practise'], name='idx_options_practise'),
        ),
        migrations.AddIndex(
            model_name='practises',
            index=models.Index(fields=['project'], name='idx_practises_project'),
        ),
        migrations.AddIndex(
            model_name='practises',
            index=models.Index(fields=['type'], name='idx_practises_type'),
        ),
        migrations.AddIndex(
            model_name='practises',
            index=models.Index(fields=['createTime'], name='idx_practises_createtime'),
        ),
        migrations.AddIndex(
            model_name='studentpracticeanswers',
            index=models.Index(fields=['practiceLog'], name='idx_practiceanswers_log'),
        ),
        migrations.AddIndex(
            model_name='studentpracticeanswers',
            index=models.Index(fields=['practise'], name='idx_practiceanswers_practise'),
        ),
        migrations.AddIndex(
            model_name='studentpracticelogs',
            index=models.Index(fields=['student'], name='idx_practicelogs_student'),
        ),
        migrations.AddIndex(
            model_name='studentpracticelogs',
            index=models.Index(fields=['paper'], name='idx_practicelogs_paper'),
        ),
        migrations.AddIndex(
            model_name='studentpracticelogs',
            index=models.Index(fields=['status'], name='idx_practicelogs_status'),
        ),
        migrations.AddIndex(
            model_name='studentpracticelogs',
            index=models.Index(fields=['startTime'], name='idx_practicelogs_starttime'),
        ),
        migrations.AddIndex(
            model_name='studenttasklogs',
            index=models.Index(fields=['student'], name='idx_tasklogs_student'),
        ),
        migrations.AddIndex(
            model_name='studenttasklogs',
            index=models.Index(fields=['task'], name='idx_tasklogs_task'),
        ),
        migrations.AddIndex(
            model_name='studenttasklogs',
            index=models.Index(fields=['status'], name='idx_tasklogs_status'),
        ),
        migrations.AddIndex(
            model_name='studenttasklogs',
            index=models.Index(fields=['startTime'], name='idx_tasklogs_starttime'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['project'], name='idx_tasks_project'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['grade'], name='idx_tasks_grade'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['teacher'], name='idx_tasks_teacher'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['isActive'], name='idx_tasks_isactive'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['createTime'], name='idx_tasks_createtime'),
        ),
    ]
