# Generated by Django 5.2.5 on 2025-08-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_practicepapers_practicepaperquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTaskLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('startTime', models.CharField(db_column='start_time', max_length=19, verbose_name='开始时间')),
                ('endTime', models.CharField(db_column='end_time', max_length=19, null=True, verbose_name='结束时间')),
                ('score', models.FloatField(default=0.0, verbose_name='得分')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='正确率')),
                ('status', models.CharField(default='in_progress', max_length=20, verbose_name='状态')),
                ('usedTime', models.IntegerField(default=0, verbose_name='用时(分钟)')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_student_task_logs',
            },
        ),
        migrations.CreateModel(
            name='StudentTaskAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('studentAnswer', models.TextField(null=True, verbose_name='学生答案')),
                ('isCorrect', models.BooleanField(null=True, verbose_name='是否正确')),
                ('score', models.FloatField(default=0.0, verbose_name='得分')),
                ('answerTime', models.CharField(db_column='answer_time', max_length=19, verbose_name='答题时间')),
                ('practise', models.ForeignKey(db_column='practise_id', on_delete=django.db.models.deletion.CASCADE, to='app.practises')),
                ('taskLog', models.ForeignKey(db_column='task_log_id', on_delete=django.db.models.deletion.CASCADE, to='app.studenttasklogs')),
            ],
            options={
                'db_table': 'fater_student_task_answers',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('title', models.CharField(max_length=128, verbose_name='任务标题')),
                ('description', models.TextField(null=True, verbose_name='任务描述')),
                ('type', models.CharField(max_length=20, verbose_name='任务类型')),
                ('deadline', models.CharField(max_length=19, verbose_name='截止时间')),
                ('score', models.IntegerField(verbose_name='任务分值')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='创建时间')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否启用')),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.CASCADE, to='app.grades')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'fater_tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('questionOrder', models.IntegerField(verbose_name='题目顺序')),
                ('score', models.FloatField(verbose_name='题目分值')),
                ('practise', models.ForeignKey(db_column='practise_id', on_delete=django.db.models.deletion.CASCADE, to='app.practises')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='app.tasks')),
            ],
            options={
                'db_table': 'fater_task_questions',
            },
        ),
        migrations.AddField(
            model_name='studenttasklogs',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='app.tasks'),
        ),
    ]
