# Generated by Django 5.2.5 on 2025-08-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studenttasklogs_studenttaskanswers_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('title', models.CharField(max_length=128, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('type', models.CharField(default='notice', max_length=20, verbose_name='消息类型')),
                ('priority', models.CharField(default='medium', max_length=20, verbose_name='优先级')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='app.users', to_field='id')),
            ],
            options={
                'db_table': 'fater_messages',
            },
        ),
        migrations.CreateModel(
            name='MessageReads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('isRead', models.BooleanField(default=False, verbose_name='是否已读')),
                ('readTime', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.users', to_field='id')),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, to='app.messages')),
            ],
            options={
                'db_table': 'fater_message_reads',
            },
        ),

        migrations.CreateModel(
            name='WrongQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('source', models.CharField(max_length=20, verbose_name='错题来源')),
                ('sourceId', models.IntegerField(verbose_name='来源ID')),
                ('wrongAnswer', models.TextField(null=True, verbose_name='错误答案')),
                ('correctAnswer', models.TextField(null=True, verbose_name='正确答案')),
                ('analysis', models.TextField(null=True, verbose_name='错题分析')),
                ('isReviewed', models.BooleanField(default=False, verbose_name='是否已复习')),
                ('reviewCount', models.IntegerField(default=0, verbose_name='复习次数')),
                ('lastReviewTime', models.CharField(db_column='last_review_time', max_length=19, null=True, verbose_name='最后复习时间')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, null=True, verbose_name='添加时间')),
                ('practise', models.ForeignKey(db_column='practise_id', on_delete=django.db.models.deletion.CASCADE, to='app.practises')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='app.users', to_field='id')),
            ],
            options={
                'db_table': 'fater_wrong_questions',
            },
        ),
        migrations.CreateModel(
            name='WrongQuestionReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('reviewAnswer', models.TextField(null=True, verbose_name='复习答案')),
                ('isCorrect', models.BooleanField(null=True, verbose_name='是否正确')),
                ('reviewTime', models.CharField(db_column='review_time', max_length=19, null=True, verbose_name='复习时间')),
                ('notes', models.TextField(null=True, verbose_name='复习笔记')),
                ('wrongQuestion', models.ForeignKey(db_column='wrong_question_id', on_delete=django.db.models.deletion.CASCADE, to='app.wrongquestions')),
            ],
            options={
                'db_table': 'fater_wrong_question_reviews',
            },
        ),
    ]
