# Generated by Django 5.2.5 on 2025-08-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_messages_messagereads_userlogs_wrongquestions_and_more'),
    ]

    operations = [
    ]
