# Generated by Django 5.2.5 on 2025-08-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_messagereads_user_alter_messages_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpracticeanswers',
            name='aiAnalysis',
            field=models.TextField(null=True, verbose_name='AI分析'),
        ),
        migrations.AddField(
            model_name='studentpracticeanswers',
            name='aiConfidence',
            field=models.FloatField(null=True, verbose_name='AI置信度'),
        ),
        migrations.AddField(
            model_name='studentpracticeanswers',
            name='aiFeedback',
            field=models.TextField(null=True, verbose_name='AI反馈'),
        ),
        migrations.AddField(
            model_name='studentpracticeanswers',
            name='aiModel',
            field=models.CharField(max_length=128, null=True, verbose_name='AI模型'),
        ),
        migrations.AddField(
            model_name='studenttaskanswers',
            name='aiAnalysis',
            field=models.TextField(null=True, verbose_name='AI分析'),
        ),
        migrations.AddField(
            model_name='studenttaskanswers',
            name='aiConfidence',
            field=models.FloatField(null=True, verbose_name='AI置信度'),
        ),
        migrations.AddField(
            model_name='studenttaskanswers',
            name='aiFeedback',
            field=models.TextField(null=True, verbose_name='AI反馈'),
        ),
        migrations.AddField(
            model_name='studenttaskanswers',
            name='aiModel',
            field=models.CharField(max_length=128, null=True, verbose_name='AI模型'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['userName'], name='idx_users_username'),
        ),
    ]
