# Generated by Django 4.1.3 on 2025-12-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_messageattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passWord',
            field=models.CharField(db_column='pass_word', max_length=128, verbose_name='用户密码'),
        ),
        migrations.DeleteModel(
            name='MessageAttachments',
        ),
    ]
